const constant ={
    BASEURL:'http://app-pccc.yez.vn/api/',
    // BASEURL:'http://giaxd.com/',
    BASE_SOCKET:'http://app-pccc.yez.vn:6006',
    SERVER_TIMEOUT:10000,
    USER: 'user',
    UPDATE_PHONE:'update-phone',
    LOGIN: 'login',
    LOGIN_SOCIAL: 'login-social',
    CHECK_PHONE_EMAIL: 'check-phone-email',
    UPDATE_AVATAR :'update-avatar',
    SELL_PRODUCT:'sell-product',
    LIQUIDATION:'liquidation',
    FORGOT_PASS:'forgot-password',
    NEW_BIDDING:'new-bidding',
    CHANGE_PASSWORD:'change-password',
    SEARCH:'search',
    PROJECT_DETAIL:'project-detail/',
    NEW_PROJECT:'new-project',
    FOLOW:'add-follows',
    UNFOLOW:'del-follows',
    LIST_FOLLOW:'list-object-follows',
    Document:'document',
    Notification:'notification',
    Data_other:'data-other',
    List_Investor:'list-investor',
    Investor_Detail:'investor-detail/',
    LIST_FOLLOW_DOCUMMENT: 'list-document-follow',
    COUNT_NOTIFICATION:'count-notification',
    LIST_LIQUIDATION:'new-post',
    UPDATE_LIQUIDATION:'update-post',
    MESSAGE:'message-chat',
    LIST_MESSAGE:'list-chat',
    STATUS_FOLLOW:'status-follow'
}

export default constant;