# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fireProtection' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fireProtection

	pod 'XCDYouTubeKit', '~> 2.5'
	pod 'GoogleSignIn'

  target 'fireProtectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fireProtection-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fireProtection-tvOS

  target 'fireProtection-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
