# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fireProtection' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fireProtection
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

	pod 'XCDYouTubeKit', '~> 2.5'
	pod 'GoogleSignIn'

  pod 'react-native-youtube', :path => '../node_modules/react-native-youtube'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'


  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'


  target 'fireProtectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fireProtection-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fireProtection-tvOS

  target 'fireProtection-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

swift4 = ['Charts']
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if swift4.include?(target.name)
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end

    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

install! 'cocoapods',
         :deterministic_uuids => false