export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_UPDATE = 'USER_UPDATE';
export const COUNT_NOTIFICATION = 'COUNT_NOTIFICATION'
export const COUNT_PROJECT ="COUNT_PROJECT"
export const COUNT_BIDDING ="COUNT_BIDDING"
export const COUNT_PRODUCT ="COUNT_PRODUCT"
export const COUNT_CONTRACTOR ="COUNT_CONTRACTOR"

